### ISSUE TITLE
[Issue]: tests missing

### ISSUE THREAD

**Issue by yiakwy-xpu-ml-framework-team** [ROCm/libhipcxx#3]
### Problem Description

Libcucxx contains tests in **.upstream-tests/test**. But we don't have them. And leaving a empty symbol test pointing to this folder in the project.

This requires us disable tests:

> cmake .. -DLIBHIPCXX_ENABLE_LIBHIPCXX_TESTS=OFF

to get build successful.

### Operating System

Ubuntu 22.04

### CPU

AMD EPYC 9534 64-Core Processor

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.2.0

### ROCm Component

HIP

### Steps to Reproduce

N/A

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

N/A

**Comment by monoatamd** [comment]
Fixed in latest update
